In [1]:
# import modules
import numpy as np 

In [2]:
# generate random data which basically performs square root function
Nargs = 11
sample_args = np.linspace(0,100,Nargs)
sample_vals = np.sqrt(sample_args)
print(sample_args)
print(sample_vals)


[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 0.          3.16227766  4.47213595  5.47722558  6.32455532  7.07106781
  7.74596669  8.36660027  8.94427191  9.48683298 10.        ]


In [3]:
# write generated data to file for further reading
filename = "sample_data.txt"
np.savetxt(filename, np.column_stack((sample_args, sample_vals)))


In [4]:
# load all data from file
args, vals = np.loadtxt(filename, unpack=True)
print("\n\n--> All data loaded and arguments and values are stored in seperate arrays: \n")
print(args)
print(vals)



--> All data loaded and arguments and values are stored in seperate arrays: 

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 0.          3.16227766  4.47213595  5.47722558  6.32455532  7.07106781
  7.74596669  8.36660027  8.94427191  9.48683298 10.        ]


In [5]:
# grab only values
vals = np.loadtxt(filename, usecols=(1))
print("\n\n--> Only value column is loaded from file: \n")
print(vals)



--> Only value column is loaded from file: 

[ 0.          3.16227766  4.47213595  5.47722558  6.32455532  7.07106781
  7.74596669  8.36660027  8.94427191  9.48683298 10.        ]


In [6]:
# skip first 5 rows then load all
'''first add dummy header to the file with new line below'''
header = "Dummy header for data file"
with open("sample_data.txt", 'r+') as f:
    content = f.read()
    f.seek(0, 0)
    f.write(header.rstrip('\r\n') + '\n\n' + content)

In [7]:
vals = np.loadtxt(filename, usecols=(1), skiprows=2)
print("\n\n--> Header is ignored and only data is retrieved: \n")
print(vals)



--> Header is ignored and only data is retrieved: 

[ 0.          3.16227766  4.47213595  5.47722558  6.32455532  7.07106781
  7.74596669  8.36660027  8.94427191  9.48683298 10.        ]


In [8]:
# load specific lines of file
'''differently from above itertools to slice file portion'''
vals = np.loadtxt(filename, usecols=(1), skiprows=7, max_rows=3)
print("\n\n--> Line datas between 6-8 loaded only: \n")
print(vals)



--> Line datas between 6-8 loaded only: 

[7.07106781 7.74596669 8.36660027]
